<?php

declare(strict_types=1);

namespace Digitix\FrameworkBundle\Translation;

use Digitix\FrameworkBundle\Repository\TranslationRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Dumps the translated values of the database as regular Symfony catalogue
 * files ("<output_dir>/<locale>/<Domain>.<locale>.php"), then invalidates
 * the translator caches so the change is visible on the next request,
 * without a full cache:clear.
 *
 * The files are an artefact: never edit them, never commit them.
 */
final class TranslationCompiler
{
    private readonly Filesystem $filesystem;

    public function __construct(
        private readonly TranslationRepository $repository,
        private readonly string $outputDir,
        private readonly string $translatorCacheDir,
        private readonly TranslatorInterface $translator,
    ) {
        $this->filesystem = new Filesystem();
    }

    public function getOutputDir(): string
    {
        return $this->outputDir;
    }

    /**
     * @param string|null $locale one locale, or every locale when null
     *
     * @return string[] files written
     */
    public function compile(?string $locale = null): array
    {
        $grouped = $this->repository->findValuesGroupedByLocale($locale);
        $locales = null === $locale
            ? array_unique(array_merge($this->existingLocaleDirs(), array_keys($grouped)))
            : [$locale];

        $files = [];

        foreach ($locales as $currentLocale) {
            $dir = $this->outputDir.'/'.$currentLocale;
            $messagesByDomain = $grouped[$currentLocale] ?? [];

            // domains without any translated key left (RuntimeFileLoader tolerates the deletion)
            foreach (glob($dir.'/*.php') ?: [] as $stale) {
                $domain = self::domainOf($stale, $currentLocale);
                if (null !== $domain && !isset($messagesByDomain[$domain])) {
                    $this->filesystem->remove($stale);
                }
            }

            foreach ($messagesByDomain as $domain => $messages) {
                $files[] = $this->dump(sprintf('%s/%s.%s.php', $dir, $domain, $currentLocale), $messages);
            }
        }

        $this->invalidateTranslatorCache();

        if ($this->translator instanceof RuntimeTranslator) {
            foreach ($files as $file) {
                $this->translator->registerRuntimeFile($file);
            }
            $this->translator->flushCatalogues();
        }

        return $files;
    }

    /**
     * @param array<string, string> $messages
     */
    private function dump(string $file, array $messages): string
    {
        $this->filesystem->dumpFile(
            $file,
            "<?php\n\n// Generated by digitix/framework-bundle from the database: edit translations in the admin, not here.\n\nreturn ".var_export($messages, true).";\n"
        );

        if (\function_exists('opcache_invalidate')) {
            @opcache_invalidate($file, true);
        }

        return $file;
    }

    /**
     * Symfony caches one file per locale, fallback catalogues included, so
     * every locale is invalidated whatever locale was compiled.
     */
    private function invalidateTranslatorCache(): void
    {
        foreach (glob($this->translatorCacheDir.'/catalogue.*') ?: [] as $file) {
            if (\function_exists('opcache_invalidate') && str_ends_with($file, '.php')) {
                @opcache_invalidate($file, true);
            }

            $this->filesystem->remove($file);
        }
    }

    /** @return string[] */
    private function existingLocaleDirs(): array
    {
        return array_map('basename', glob($this->outputDir.'/*', \GLOB_ONLYDIR) ?: []);
    }

    private static function domainOf(string $file, string $locale): ?string
    {
        $suffix = '.'.$locale.'.php';
        $name = basename($file);

        return str_ends_with($name, $suffix) ? substr($name, 0, -\strlen($suffix)) : null;
    }
}
